version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/sampleApp
  - source: /config/*.conf
    destination: /etc/apache2/sites-available/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
runas: root